version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invitedoc
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://user:password@db:5432/invitedoc?sslmode=disable
    depends_on:
      - db
    command: air

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    depends_on:
      - app
