// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type GroupMember struct {
	ID        uuid.UUID `json:"id"`
	ContactID uuid.UUID `json:"contact_id"`
	GroupID   uuid.UUID `json:"group_id"`
}

type Invite struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	From        time.Time      `json:"from"`
	To          sql.NullTime   `json:"to"`
	Duration    sql.NullInt64  `json:"duration"`
	CreatedAt   time.Time      `json:"created_at"`
	Status      string         `json:"status"`
}

type InvitePhase struct {
	ID             uuid.UUID       `json:"id"`
	InviteID       uuid.UUID       `json:"invite_id"`
	Order          int32           `json:"order"`
	StrategyKind   string          `json:"strategy_kind"`
	StrategyConfig json.RawMessage `json:"strategy_config"`
}

type InvitePhaseState struct {
	PhaseID     uuid.UUID       `json:"phase_id"`
	Status      string          `json:"status"`
	NextCheckAt sql.NullTime    `json:"next_check_at"`
	Data        json.RawMessage `json:"data"`
}

type Invitee struct {
	ID         uuid.UUID `json:"id"`
	InviteID   uuid.UUID `json:"invite_id"`
	ContactID  uuid.UUID `json:"contact_id"`
	State      string    `json:"state"`
	CreatedAt  time.Time `json:"created_at"`
	MagicToken uuid.UUID `json:"magic_token"`
}

type Person struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}
