// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (id, contact_id, group_id)
VALUES ($1, $2, $3)
`

type AddGroupMemberParams struct {
	ID        uuid.UUID `json:"id"`
	ContactID uuid.UUID `json:"contact_id"`
	GroupID   uuid.UUID `json:"group_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.ID, arg.ContactID, arg.GroupID)
	return err
}

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM persons WHERE password_hash IS NOT NULL
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailLog = `-- name: CreateEmailLog :one
INSERT INTO email_logs (id, invitee_id, recipient_email, subject, body, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, invitee_id, recipient_email, subject, body, status, error_message, attempts, last_attempt_at, created_at
`

type CreateEmailLogParams struct {
	ID             uuid.UUID     `json:"id"`
	InviteeID      uuid.NullUUID `json:"invitee_id"`
	RecipientEmail string        `json:"recipient_email"`
	Subject        string        `json:"subject"`
	Body           string        `json:"body"`
	Status         string        `json:"status"`
}

func (q *Queries) CreateEmailLog(ctx context.Context, arg CreateEmailLogParams) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, createEmailLog,
		arg.ID,
		arg.InviteeID,
		arg.RecipientEmail,
		arg.Subject,
		arg.Body,
		arg.Status,
	)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.InviteeID,
		&i.RecipientEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ErrorMessage,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, description)
VALUES ($1, $2, $3)
RETURNING id, name, description
`

type CreateGroupParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, title, description, "from", "to", duration, created_at, status, from_person_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, "from", "to", duration, created_at, status, from_person_id
`

type CreateInviteParams struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	From         time.Time      `json:"from"`
	To           sql.NullTime   `json:"to"`
	Duration     sql.NullInt64  `json:"duration"`
	CreatedAt    time.Time      `json:"created_at"`
	Status       string         `json:"status"`
	FromPersonID uuid.NullUUID  `json:"from_person_id"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.From,
		arg.To,
		arg.Duration,
		arg.CreatedAt,
		arg.Status,
		arg.FromPersonID,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.From,
		&i.To,
		&i.Duration,
		&i.CreatedAt,
		&i.Status,
		&i.FromPersonID,
	)
	return i, err
}

const createInvitePhase = `-- name: CreateInvitePhase :one
INSERT INTO invite_phases (id, invite_id, "order", strategy_kind, strategy_config)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invite_id, "order", strategy_kind, strategy_config
`

type CreateInvitePhaseParams struct {
	ID             uuid.UUID       `json:"id"`
	InviteID       uuid.UUID       `json:"invite_id"`
	Order          int32           `json:"order"`
	StrategyKind   string          `json:"strategy_kind"`
	StrategyConfig json.RawMessage `json:"strategy_config"`
}

func (q *Queries) CreateInvitePhase(ctx context.Context, arg CreateInvitePhaseParams) (InvitePhase, error) {
	row := q.db.QueryRowContext(ctx, createInvitePhase,
		arg.ID,
		arg.InviteID,
		arg.Order,
		arg.StrategyKind,
		arg.StrategyConfig,
	)
	var i InvitePhase
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.Order,
		&i.StrategyKind,
		&i.StrategyConfig,
	)
	return i, err
}

const createInvitee = `-- name: CreateInvitee :exec
INSERT INTO invitees (id, invite_id, contact_id, state, created_at, magic_token)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInviteeParams struct {
	ID         uuid.UUID `json:"id"`
	InviteID   uuid.UUID `json:"invite_id"`
	ContactID  uuid.UUID `json:"contact_id"`
	State      string    `json:"state"`
	CreatedAt  time.Time `json:"created_at"`
	MagicToken uuid.UUID `json:"magic_token"`
}

func (q *Queries) CreateInvitee(ctx context.Context, arg CreateInviteeParams) error {
	_, err := q.db.ExecContext(ctx, createInvitee,
		arg.ID,
		arg.InviteID,
		arg.ContactID,
		arg.State,
		arg.CreatedAt,
		arg.MagicToken,
	)
	return err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (id, email, name, password_hash) VALUES ($1, $2, $3, $4) RETURNING id, email, name, password_hash, password_reset_token, password_reset_expires_at
`

type CreatePersonParams struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const createPhaseState = `-- name: CreatePhaseState :exec
INSERT INTO invite_phase_state (phase_id, status, next_check_at, data)
VALUES ($1, $2, $3, $4)
`

type CreatePhaseStateParams struct {
	PhaseID     uuid.UUID       `json:"phase_id"`
	Status      string          `json:"status"`
	NextCheckAt sql.NullTime    `json:"next_check_at"`
	Data        json.RawMessage `json:"data"`
}

func (q *Queries) CreatePhaseState(ctx context.Context, arg CreatePhaseStateParams) error {
	_, err := q.db.ExecContext(ctx, createPhaseState,
		arg.PhaseID,
		arg.Status,
		arg.NextCheckAt,
		arg.Data,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, person_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, person_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	PersonID  uuid.UUID `json:"person_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.PersonID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, id)
	return err
}

const deleteInvitePhase = `-- name: DeleteInvitePhase :exec
DELETE FROM invite_phases WHERE id = $1 AND invite_id = $2
`

type DeleteInvitePhaseParams struct {
	ID       uuid.UUID `json:"id"`
	InviteID uuid.UUID `json:"invite_id"`
}

func (q *Queries) DeleteInvitePhase(ctx context.Context, arg DeleteInvitePhaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteInvitePhase, arg.ID, arg.InviteID)
	return err
}

const deleteInvitePhaseStates = `-- name: DeleteInvitePhaseStates :exec
DELETE FROM invite_phase_state 
WHERE phase_id IN (SELECT id FROM invite_phases WHERE invite_id = $1)
`

func (q *Queries) DeleteInvitePhaseStates(ctx context.Context, inviteID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvitePhaseStates, inviteID)
	return err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePerson, id)
	return err
}

const deletePhaseState = `-- name: DeletePhaseState :exec
DELETE FROM invite_phase_state WHERE phase_id = $1
`

func (q *Queries) DeletePhaseState(ctx context.Context, phaseID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePhaseState, phaseID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getActivePhaseForInvite = `-- name: GetActivePhaseForInvite :one
SELECT 
    p.id AS phase_id,
    p.invite_id,
    p."order",
    p.strategy_kind,
    p.strategy_config,
    s.status AS phase_status,
    s.next_check_at,
    s.data AS phase_data
FROM invite_phase_state s
JOIN invite_phases p ON s.phase_id = p.id
WHERE p.invite_id = $1 AND s.status = 'active'
`

type GetActivePhaseForInviteRow struct {
	PhaseID        uuid.UUID       `json:"phase_id"`
	InviteID       uuid.UUID       `json:"invite_id"`
	Order          int32           `json:"order"`
	StrategyKind   string          `json:"strategy_kind"`
	StrategyConfig json.RawMessage `json:"strategy_config"`
	PhaseStatus    string          `json:"phase_status"`
	NextCheckAt    sql.NullTime    `json:"next_check_at"`
	PhaseData      json.RawMessage `json:"phase_data"`
}

func (q *Queries) GetActivePhaseForInvite(ctx context.Context, inviteID uuid.UUID) (GetActivePhaseForInviteRow, error) {
	row := q.db.QueryRowContext(ctx, getActivePhaseForInvite, inviteID)
	var i GetActivePhaseForInviteRow
	err := row.Scan(
		&i.PhaseID,
		&i.InviteID,
		&i.Order,
		&i.StrategyKind,
		&i.StrategyConfig,
		&i.PhaseStatus,
		&i.NextCheckAt,
		&i.PhaseData,
	)
	return i, err
}

const getActivePhasesToProcess = `-- name: GetActivePhasesToProcess :many
SELECT 
    p.id AS phase_id,
    p.invite_id,
    p."order",
    p.strategy_kind,
    p.strategy_config,
    s.status AS phase_status,
    s.next_check_at,
    s.data AS phase_data,
    i.title,
    i.description,
    i."from",
    i."to",
    i.duration,
    i.created_at,
    i.status AS invite_status,
    i.from_person_id
FROM invite_phase_state s
JOIN invite_phases p ON s.phase_id = p.id
JOIN invites i ON p.invite_id = i.id
WHERE s.status = 'active' 
  AND (s.next_check_at IS NULL OR s.next_check_at <= $1)
`

type GetActivePhasesToProcessRow struct {
	PhaseID        uuid.UUID       `json:"phase_id"`
	InviteID       uuid.UUID       `json:"invite_id"`
	Order          int32           `json:"order"`
	StrategyKind   string          `json:"strategy_kind"`
	StrategyConfig json.RawMessage `json:"strategy_config"`
	PhaseStatus    string          `json:"phase_status"`
	NextCheckAt    sql.NullTime    `json:"next_check_at"`
	PhaseData      json.RawMessage `json:"phase_data"`
	Title          string          `json:"title"`
	Description    sql.NullString  `json:"description"`
	From           time.Time       `json:"from"`
	To             sql.NullTime    `json:"to"`
	Duration       sql.NullInt64   `json:"duration"`
	CreatedAt      time.Time       `json:"created_at"`
	InviteStatus   string          `json:"invite_status"`
	FromPersonID   uuid.NullUUID   `json:"from_person_id"`
}

func (q *Queries) GetActivePhasesToProcess(ctx context.Context, nextCheckAt sql.NullTime) ([]GetActivePhasesToProcessRow, error) {
	rows, err := q.db.QueryContext(ctx, getActivePhasesToProcess, nextCheckAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePhasesToProcessRow
	for rows.Next() {
		var i GetActivePhasesToProcessRow
		if err := rows.Scan(
			&i.PhaseID,
			&i.InviteID,
			&i.Order,
			&i.StrategyKind,
			&i.StrategyConfig,
			&i.PhaseStatus,
			&i.NextCheckAt,
			&i.PhaseData,
			&i.Title,
			&i.Description,
			&i.From,
			&i.To,
			&i.Duration,
			&i.CreatedAt,
			&i.InviteStatus,
			&i.FromPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailLog = `-- name: GetEmailLog :one
SELECT id, invitee_id, recipient_email, subject, body, status, error_message, attempts, last_attempt_at, created_at FROM email_logs WHERE id = $1
`

func (q *Queries) GetEmailLog(ctx context.Context, id uuid.UUID) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, getEmailLog, id)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.InviteeID,
		&i.RecipientEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ErrorMessage,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailLogByInvitee = `-- name: GetEmailLogByInvitee :one
SELECT id, invitee_id, recipient_email, subject, body, status, error_message, attempts, last_attempt_at, created_at FROM email_logs WHERE invitee_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetEmailLogByInvitee(ctx context.Context, inviteeID uuid.NullUUID) (EmailLog, error) {
	row := q.db.QueryRowContext(ctx, getEmailLogByInvitee, inviteeID)
	var i EmailLog
	err := row.Scan(
		&i.ID,
		&i.InviteeID,
		&i.RecipientEmail,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.ErrorMessage,
		&i.Attempts,
		&i.LastAttemptAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFailedEmails = `-- name: GetFailedEmails :many
SELECT id, invitee_id, recipient_email, subject, body, status, error_message, attempts, last_attempt_at, created_at FROM email_logs WHERE status = 'failed' AND attempts < 3
`

func (q *Queries) GetFailedEmails(ctx context.Context) ([]EmailLog, error) {
	rows, err := q.db.QueryContext(ctx, getFailedEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLog
	for rows.Next() {
		var i EmailLog
		if err := rows.Scan(
			&i.ID,
			&i.InviteeID,
			&i.RecipientEmail,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.ErrorMessage,
			&i.Attempts,
			&i.LastAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstInvitePhase = `-- name: GetFirstInvitePhase :one
SELECT id, invite_id, "order", strategy_kind, strategy_config FROM invite_phases 
WHERE invite_id = $1 
ORDER BY "order" ASC 
LIMIT 1
`

func (q *Queries) GetFirstInvitePhase(ctx context.Context, inviteID uuid.UUID) (InvitePhase, error) {
	row := q.db.QueryRowContext(ctx, getFirstInvitePhase, inviteID)
	var i InvitePhase
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.Order,
		&i.StrategyKind,
		&i.StrategyConfig,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, title, description, "from", "to", duration, created_at, status, from_person_id FROM invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.From,
		&i.To,
		&i.Duration,
		&i.CreatedAt,
		&i.Status,
		&i.FromPersonID,
	)
	return i, err
}

const getInvitePhase = `-- name: GetInvitePhase :one
SELECT id, invite_id, "order", strategy_kind, strategy_config FROM invite_phases WHERE id = $1
`

func (q *Queries) GetInvitePhase(ctx context.Context, id uuid.UUID) (InvitePhase, error) {
	row := q.db.QueryRowContext(ctx, getInvitePhase, id)
	var i InvitePhase
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.Order,
		&i.StrategyKind,
		&i.StrategyConfig,
	)
	return i, err
}

const getInvitee = `-- name: GetInvitee :one
SELECT id, invite_id, contact_id, state, created_at, magic_token FROM invitees WHERE id = $1
`

func (q *Queries) GetInvitee(ctx context.Context, id uuid.UUID) (Invitee, error) {
	row := q.db.QueryRowContext(ctx, getInvitee, id)
	var i Invitee
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.ContactID,
		&i.State,
		&i.CreatedAt,
		&i.MagicToken,
	)
	return i, err
}

const getInviteeByToken = `-- name: GetInviteeByToken :one
SELECT i.id, i.invite_id, i.contact_id, i.state, i.created_at, i.magic_token, inv.title, inv.description as invite_description, inv."from", inv."to"
FROM invitees i
JOIN invites inv ON i.invite_id = inv.id
WHERE i.magic_token = $1
`

type GetInviteeByTokenRow struct {
	ID                uuid.UUID      `json:"id"`
	InviteID          uuid.UUID      `json:"invite_id"`
	ContactID         uuid.UUID      `json:"contact_id"`
	State             string         `json:"state"`
	CreatedAt         time.Time      `json:"created_at"`
	MagicToken        uuid.UUID      `json:"magic_token"`
	Title             string         `json:"title"`
	InviteDescription sql.NullString `json:"invite_description"`
	From              time.Time      `json:"from"`
	To                sql.NullTime   `json:"to"`
}

func (q *Queries) GetInviteeByToken(ctx context.Context, magicToken uuid.UUID) (GetInviteeByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getInviteeByToken, magicToken)
	var i GetInviteeByTokenRow
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.ContactID,
		&i.State,
		&i.CreatedAt,
		&i.MagicToken,
		&i.Title,
		&i.InviteDescription,
		&i.From,
		&i.To,
	)
	return i, err
}

const getInviteesStatus = `-- name: GetInviteesStatus :many
SELECT p.id, p.email, p.name, i.created_at AS invited_at, i.state AS status, i.magic_token
FROM invitees i
JOIN persons p ON i.contact_id = p.id
WHERE i.invite_id = $1
ORDER BY i.created_at ASC
`

type GetInviteesStatusRow struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	Name       string    `json:"name"`
	InvitedAt  time.Time `json:"invited_at"`
	Status     string    `json:"status"`
	MagicToken uuid.UUID `json:"magic_token"`
}

func (q *Queries) GetInviteesStatus(ctx context.Context, inviteID uuid.UUID) ([]GetInviteesStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getInviteesStatus, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInviteesStatusRow
	for rows.Next() {
		var i GetInviteesStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.InvitedAt,
			&i.Status,
			&i.MagicToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextInvitePhase = `-- name: GetNextInvitePhase :one
SELECT id, invite_id, "order", strategy_kind, strategy_config FROM invite_phases
WHERE invite_id = $1 AND "order" > $2
ORDER BY "order" ASC
LIMIT 1
`

type GetNextInvitePhaseParams struct {
	InviteID uuid.UUID `json:"invite_id"`
	Order    int32     `json:"order"`
}

func (q *Queries) GetNextInvitePhase(ctx context.Context, arg GetNextInvitePhaseParams) (InvitePhase, error) {
	row := q.db.QueryRowContext(ctx, getNextInvitePhase, arg.InviteID, arg.Order)
	var i InvitePhase
	err := row.Scan(
		&i.ID,
		&i.InviteID,
		&i.Order,
		&i.StrategyKind,
		&i.StrategyConfig,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, email, name, password_hash, password_reset_token, password_reset_expires_at FROM persons WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, email, name, password_hash, password_reset_token, password_reset_expires_at FROM persons WHERE email = $1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByEmail, email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getPersonByResetToken = `-- name: GetPersonByResetToken :one
SELECT id, email, name, password_hash, password_reset_token, password_reset_expires_at FROM persons 
WHERE password_reset_token = $1 
  AND password_reset_expires_at > NOW()
`

func (q *Queries) GetPersonByResetToken(ctx context.Context, passwordResetToken sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByResetToken, passwordResetToken)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.person_id, s.expires_at, s.created_at, p.email, p.name, p.password_hash
FROM sessions s
JOIN persons p ON s.person_id = p.id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetSessionRow struct {
	ID           uuid.UUID      `json:"id"`
	PersonID     uuid.UUID      `json:"person_id"`
	ExpiresAt    time.Time      `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT p.id, p.email, p.name, p.password_hash, p.password_reset_token, p.password_reset_expires_at FROM persons p
JOIN group_members gm ON p.id = gm.contact_id
WHERE gm.group_id = $1
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.PasswordResetToken,
			&i.PasswordResetExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitePhases = `-- name: ListInvitePhases :many
SELECT id, invite_id, "order", strategy_kind, strategy_config FROM invite_phases WHERE invite_id = $1 ORDER BY "order" ASC
`

func (q *Queries) ListInvitePhases(ctx context.Context, inviteID uuid.UUID) ([]InvitePhase, error) {
	rows, err := q.db.QueryContext(ctx, listInvitePhases, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvitePhase
	for rows.Next() {
		var i InvitePhase
		if err := rows.Scan(
			&i.ID,
			&i.InviteID,
			&i.Order,
			&i.StrategyKind,
			&i.StrategyConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvites = `-- name: ListInvites :many
SELECT id, title, description, "from", "to", duration, created_at, status, from_person_id FROM invites
`

func (q *Queries) ListInvites(ctx context.Context) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.From,
			&i.To,
			&i.Duration,
			&i.CreatedAt,
			&i.Status,
			&i.FromPersonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersons = `-- name: ListPersons :many
SELECT id, email, name, password_hash, password_reset_token, password_reset_expires_at FROM persons
`

func (q *Queries) ListPersons(ctx context.Context) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.PasswordResetToken,
			&i.PasswordResetExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND contact_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID   uuid.UUID `json:"group_id"`
	ContactID uuid.UUID `json:"contact_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.ContactID)
	return err
}

const resolveRecipients = `-- name: ResolveRecipients :many
SELECT p.id, p.email, p.name
FROM persons p
WHERE p.id = ANY($1::uuid[])
OR p.id IN (
    SELECT contact_id FROM group_members WHERE group_id = ANY($1::uuid[])
)
`

type ResolveRecipientsRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
	Name  string    `json:"name"`
}

func (q *Queries) ResolveRecipients(ctx context.Context, dollar_1 []uuid.UUID) ([]ResolveRecipientsRow, error) {
	rows, err := q.db.QueryContext(ctx, resolveRecipients, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveRecipientsRow
	for rows.Next() {
		var i ResolveRecipientsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondToInvite = `-- name: RespondToInvite :exec
UPDATE invitees SET state = $2 WHERE magic_token = $1
`

type RespondToInviteParams struct {
	MagicToken uuid.UUID `json:"magic_token"`
	State      string    `json:"state"`
}

func (q *Queries) RespondToInvite(ctx context.Context, arg RespondToInviteParams) error {
	_, err := q.db.ExecContext(ctx, respondToInvite, arg.MagicToken, arg.State)
	return err
}

const updateEmailLogStatus = `-- name: UpdateEmailLogStatus :exec
UPDATE email_logs
SET status = $2, error_message = $3, attempts = attempts + 1, last_attempt_at = NOW()
WHERE id = $1
`

type UpdateEmailLogStatusParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) UpdateEmailLogStatus(ctx context.Context, arg UpdateEmailLogStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmailLogStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET 
    name = COALESCE($1, name),
    description = COALESCE($2, description)
WHERE id = $3
RETURNING id, name, description
`

type UpdateGroupParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.Name, arg.Description, arg.ID)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const updateInvite = `-- name: UpdateInvite :one
UPDATE invites
SET 
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    "from" = COALESCE($3, "from"),
    "to" = COALESCE($4, "to"),
    duration = COALESCE($5, duration),
    status = COALESCE($6, status),
    from_person_id = COALESCE($7, from_person_id)
WHERE id = $8
RETURNING id, title, description, "from", "to", duration, created_at, status, from_person_id
`

type UpdateInviteParams struct {
	Title        sql.NullString `json:"title"`
	Description  sql.NullString `json:"description"`
	From         sql.NullTime   `json:"from"`
	To           sql.NullTime   `json:"to"`
	Duration     sql.NullInt64  `json:"duration"`
	Status       sql.NullString `json:"status"`
	FromPersonID uuid.NullUUID  `json:"from_person_id"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateInvite(ctx context.Context, arg UpdateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, updateInvite,
		arg.Title,
		arg.Description,
		arg.From,
		arg.To,
		arg.Duration,
		arg.Status,
		arg.FromPersonID,
		arg.ID,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.From,
		&i.To,
		&i.Duration,
		&i.CreatedAt,
		&i.Status,
		&i.FromPersonID,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET 
    email = COALESCE($1, email),
    name = COALESCE($2, name),
    password_hash = COALESCE($3, password_hash)
WHERE id = $4
RETURNING id, email, name, password_hash, password_reset_token, password_reset_expires_at
`

type UpdatePersonParams struct {
	Email        sql.NullString `json:"email"`
	Name         sql.NullString `json:"name"`
	PasswordHash sql.NullString `json:"password_hash"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePerson,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const updatePersonAuth = `-- name: UpdatePersonAuth :one
UPDATE persons
SET 
    password_hash = COALESCE($1, password_hash),
    password_reset_token = COALESCE($2, password_reset_token),
    password_reset_expires_at = COALESCE($3, password_reset_expires_at)
WHERE id = $4
RETURNING id, email, name, password_hash, password_reset_token, password_reset_expires_at
`

type UpdatePersonAuthParams struct {
	PasswordHash           sql.NullString `json:"password_hash"`
	PasswordResetToken     sql.NullString `json:"password_reset_token"`
	PasswordResetExpiresAt sql.NullTime   `json:"password_reset_expires_at"`
	ID                     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePersonAuth(ctx context.Context, arg UpdatePersonAuthParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, updatePersonAuth,
		arg.PasswordHash,
		arg.PasswordResetToken,
		arg.PasswordResetExpiresAt,
		arg.ID,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
	)
	return i, err
}

const updatePhaseState = `-- name: UpdatePhaseState :exec
UPDATE invite_phase_state
SET status = $2, next_check_at = $3, data = $4
WHERE phase_id = $1
`

type UpdatePhaseStateParams struct {
	PhaseID     uuid.UUID       `json:"phase_id"`
	Status      string          `json:"status"`
	NextCheckAt sql.NullTime    `json:"next_check_at"`
	Data        json.RawMessage `json:"data"`
}

func (q *Queries) UpdatePhaseState(ctx context.Context, arg UpdatePhaseStateParams) error {
	_, err := q.db.ExecContext(ctx, updatePhaseState,
		arg.PhaseID,
		arg.Status,
		arg.NextCheckAt,
		arg.Data,
	)
	return err
}
