//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InviteStatus.
const (
	InviteStatusActive    InviteStatus = "active"
	InviteStatusCancelled InviteStatus = "cancelled"
	InviteStatusCompleted InviteStatus = "completed"
	InviteStatusPending   InviteStatus = "pending"
)

// Valid indicates whether the value is a known member of the InviteStatus enum.
func (e InviteStatus) Valid() bool {
	switch e {
	case InviteStatusActive:
		return true
	case InviteStatusCancelled:
		return true
	case InviteStatusCompleted:
		return true
	case InviteStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for InvitePhaseStrategyKind.
const (
	InvitePhaseStrategyKindLadder InvitePhaseStrategyKind = "ladder"
	InvitePhaseStrategyKindSprint InvitePhaseStrategyKind = "sprint"
)

// Valid indicates whether the value is a known member of the InvitePhaseStrategyKind enum.
func (e InvitePhaseStrategyKind) Valid() bool {
	switch e {
	case InvitePhaseStrategyKindLadder:
		return true
	case InvitePhaseStrategyKindSprint:
		return true
	default:
		return false
	}
}

// Defines values for NewInvitePhaseStrategyKind.
const (
	NewInvitePhaseStrategyKindLadder NewInvitePhaseStrategyKind = "ladder"
	NewInvitePhaseStrategyKindSprint NewInvitePhaseStrategyKind = "sprint"
)

// Valid indicates whether the value is a known member of the NewInvitePhaseStrategyKind enum.
func (e NewInvitePhaseStrategyKind) Valid() bool {
	switch e {
	case NewInvitePhaseStrategyKindLadder:
		return true
	case NewInvitePhaseStrategyKindSprint:
		return true
	default:
		return false
	}
}

// Defines values for UpdateInviteStatus.
const (
	UpdateInviteStatusActive    UpdateInviteStatus = "active"
	UpdateInviteStatusCancelled UpdateInviteStatus = "cancelled"
	UpdateInviteStatusCompleted UpdateInviteStatus = "completed"
	UpdateInviteStatusPending   UpdateInviteStatus = "pending"
)

// Valid indicates whether the value is a known member of the UpdateInviteStatus enum.
func (e UpdateInviteStatus) Valid() bool {
	switch e {
	case UpdateInviteStatusActive:
		return true
	case UpdateInviteStatusCancelled:
		return true
	case UpdateInviteStatusCompleted:
		return true
	case UpdateInviteStatusPending:
		return true
	default:
		return false
	}
}

// AddGroupMemberRequest defines model for AddGroupMemberRequest.
type AddGroupMemberRequest struct {
	PersonId openapi_types.UUID `json:"person_id"`
}

// Group defines model for Group.
type Group struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
}

// Invite defines model for Invite.
type Invite struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`

	// DurationNs Duration in nanoseconds
	DurationNs *int               `json:"duration_ns,omitempty"`
	From       time.Time          `json:"from"`
	Id         openapi_types.UUID `json:"id"`
	Status     InviteStatus       `json:"status"`
	Title      string             `json:"title"`
	To         *time.Time         `json:"to,omitempty"`
}

// InviteStatus defines model for Invite.Status.
type InviteStatus string

// InvitePhase defines model for InvitePhase.
type InvitePhase struct {
	Id       openapi_types.UUID `json:"id"`
	InviteId openapi_types.UUID `json:"invite_id"`
	Order    int                `json:"order"`

	// StrategyConfig JSON configuration specific to the strategy
	StrategyConfig map[string]interface{}  `json:"strategy_config"`
	StrategyKind   InvitePhaseStrategyKind `json:"strategy_kind"`
}

// InvitePhaseStrategyKind defines model for InvitePhase.StrategyKind.
type InvitePhaseStrategyKind string

// InviteStatusReport defines model for InviteStatusReport.
type InviteStatusReport struct {
	ActivePhase *struct {
		Id          *openapi_types.UUID `json:"id,omitempty"`
		NextCheckAt *time.Time          `json:"next_check_at,omitempty"`
		Order       *int                `json:"order,omitempty"`

		// ProgressMessage Human-readable progress from the strategy
		ProgressMessage *string `json:"progress_message,omitempty"`
		StrategyKind    *string `json:"strategy_kind,omitempty"`
	} `json:"active_phase,omitempty"`
	InviteId        openapi_types.UUID `json:"invite_id"`
	OverallStatus   string             `json:"overall_status"`
	PendingInvitees *[]PendingInvitee  `json:"pending_invitees,omitempty"`
}

// NewGroup defines model for NewGroup.
type NewGroup struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// NewInvite defines model for NewInvite.
type NewInvite struct {
	Description *string    `json:"description,omitempty"`
	DurationNs  *int       `json:"duration_ns,omitempty"`
	From        time.Time  `json:"from"`
	Title       string     `json:"title"`
	To          *time.Time `json:"to,omitempty"`
}

// NewInvitePhase defines model for NewInvitePhase.
type NewInvitePhase struct {
	Order          int                        `json:"order"`
	StrategyConfig map[string]interface{}     `json:"strategy_config"`
	StrategyKind   NewInvitePhaseStrategyKind `json:"strategy_kind"`
}

// NewInvitePhaseStrategyKind defines model for NewInvitePhase.StrategyKind.
type NewInvitePhaseStrategyKind string

// NewPerson defines model for NewPerson.
type NewPerson struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// PendingInvitee defines model for PendingInvitee.
type PendingInvitee struct {
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	InvitedAt time.Time           `json:"invited_at"`
	Name      string              `json:"name"`
}

// Person defines model for Person.
type Person struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
	Name  string              `json:"name"`
}

// UpdateGroup defines model for UpdateGroup.
type UpdateGroup struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateInvite defines model for UpdateInvite.
type UpdateInvite struct {
	Description *string             `json:"description,omitempty"`
	DurationNs  *int                `json:"duration_ns,omitempty"`
	From        *time.Time          `json:"from,omitempty"`
	Status      *UpdateInviteStatus `json:"status,omitempty"`
	Title       *string             `json:"title,omitempty"`
	To          *time.Time          `json:"to,omitempty"`
}

// UpdateInviteStatus defines model for UpdateInvite.Status.
type UpdateInviteStatus string

// UpdatePerson defines model for UpdatePerson.
type UpdatePerson struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Name  *string              `json:"name,omitempty"`
}

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = NewGroup

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroup

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddGroupMemberRequest

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = NewInvite

// UpdateInviteJSONRequestBody defines body for UpdateInvite for application/json ContentType.
type UpdateInviteJSONRequestBody = UpdateInvite

// CreateInvitePhaseJSONRequestBody defines body for CreateInvitePhase for application/json ContentType.
type CreateInvitePhaseJSONRequestBody = NewInvitePhase

// CreatePersonJSONRequestBody defines body for CreatePerson for application/json ContentType.
type CreatePersonJSONRequestBody = NewPerson

// UpdatePersonJSONRequestBody defines body for UpdatePerson for application/json ContentType.
type UpdatePersonJSONRequestBody = UpdatePerson

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all groups
	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request)
	// Create a new group
	// (POST /groups)
	CreateGroup(w http.ResponseWriter, r *http.Request)
	// Delete a group
	// (DELETE /groups/{id})
	DeleteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a group by ID
	// (GET /groups/{id})
	GetGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a group
	// (PATCH /groups/{id})
	UpdateGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List members of a group
	// (GET /groups/{id}/members)
	ListGroupMembers(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Add a member to a group
	// (POST /groups/{id}/members)
	AddGroupMember(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a member from a group
	// (DELETE /groups/{id}/members/{person_id})
	RemoveGroupMember(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, personId openapi_types.UUID)
	// List all invites
	// (GET /invites)
	ListInvites(w http.ResponseWriter, r *http.Request)
	// Create a new invite
	// (POST /invites)
	CreateInvite(w http.ResponseWriter, r *http.Request)
	// Delete an invite
	// (DELETE /invites/{id})
	DeleteInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get an invite by ID
	// (GET /invites/{id})
	GetInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update an invite
	// (PATCH /invites/{id})
	UpdateInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List phases for an invite
	// (GET /invites/{id}/phases)
	ListInvitePhases(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Add a phase to an invite
	// (POST /invites/{id}/phases)
	CreateInvitePhase(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Delete a phase from an invite
	// (DELETE /invites/{id}/phases/{phase_id})
	DeleteInvitePhase(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, phaseId openapi_types.UUID)
	// Start the invite process
	// (POST /invites/{id}/start)
	StartInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get current progress and pending invitees
	// (GET /invites/{id}/status)
	GetInviteStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List all persons
	// (GET /persons)
	ListPersons(w http.ResponseWriter, r *http.Request)
	// Create a new person
	// (POST /persons)
	CreatePerson(w http.ResponseWriter, r *http.Request)
	// Delete a person
	// (DELETE /persons/{id})
	DeletePerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a person by ID
	// (GET /persons/{id})
	GetPerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a person
	// (PATCH /persons/{id})
	UpdatePerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroupMembers operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMembers(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddGroupMember operation middleware
func (siw *ServerInterfaceWrapper) AddGroupMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddGroupMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveGroupMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveGroupMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "person_id" -------------
	var personId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "person_id", r.PathValue("person_id"), &personId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "person_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveGroupMember(w, r, id, personId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvites operation middleware
func (siw *ServerInterfaceWrapper) ListInvites(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateInvite(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInvite operation middleware
func (siw *ServerInterfaceWrapper) DeleteInvite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInvite operation middleware
func (siw *ServerInterfaceWrapper) GetInvite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateInvite operation middleware
func (siw *ServerInterfaceWrapper) UpdateInvite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListInvitePhases operation middleware
func (siw *ServerInterfaceWrapper) ListInvitePhases(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListInvitePhases(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateInvitePhase operation middleware
func (siw *ServerInterfaceWrapper) CreateInvitePhase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInvitePhase(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteInvitePhase operation middleware
func (siw *ServerInterfaceWrapper) DeleteInvitePhase(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "phase_id" -------------
	var phaseId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "phase_id", r.PathValue("phase_id"), &phaseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "phase_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteInvitePhase(w, r, id, phaseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartInvite operation middleware
func (siw *ServerInterfaceWrapper) StartInvite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartInvite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInviteStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInviteStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInviteStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPersons operation middleware
func (siw *ServerInterfaceWrapper) ListPersons(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPersons(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePerson operation middleware
func (siw *ServerInterfaceWrapper) CreatePerson(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePerson(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePerson operation middleware
func (siw *ServerInterfaceWrapper) DeletePerson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePerson(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPerson operation middleware
func (siw *ServerInterfaceWrapper) GetPerson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPerson(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePerson operation middleware
func (siw *ServerInterfaceWrapper) UpdatePerson(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePerson(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/groups", wrapper.ListGroups)
	m.HandleFunc("POST "+options.BaseURL+"/groups", wrapper.CreateGroup)
	m.HandleFunc("DELETE "+options.BaseURL+"/groups/{id}", wrapper.DeleteGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{id}", wrapper.GetGroup)
	m.HandleFunc("PATCH "+options.BaseURL+"/groups/{id}", wrapper.UpdateGroup)
	m.HandleFunc("GET "+options.BaseURL+"/groups/{id}/members", wrapper.ListGroupMembers)
	m.HandleFunc("POST "+options.BaseURL+"/groups/{id}/members", wrapper.AddGroupMember)
	m.HandleFunc("DELETE "+options.BaseURL+"/groups/{id}/members/{person_id}", wrapper.RemoveGroupMember)
	m.HandleFunc("GET "+options.BaseURL+"/invites", wrapper.ListInvites)
	m.HandleFunc("POST "+options.BaseURL+"/invites", wrapper.CreateInvite)
	m.HandleFunc("DELETE "+options.BaseURL+"/invites/{id}", wrapper.DeleteInvite)
	m.HandleFunc("GET "+options.BaseURL+"/invites/{id}", wrapper.GetInvite)
	m.HandleFunc("PATCH "+options.BaseURL+"/invites/{id}", wrapper.UpdateInvite)
	m.HandleFunc("GET "+options.BaseURL+"/invites/{id}/phases", wrapper.ListInvitePhases)
	m.HandleFunc("POST "+options.BaseURL+"/invites/{id}/phases", wrapper.CreateInvitePhase)
	m.HandleFunc("DELETE "+options.BaseURL+"/invites/{id}/phases/{phase_id}", wrapper.DeleteInvitePhase)
	m.HandleFunc("POST "+options.BaseURL+"/invites/{id}/start", wrapper.StartInvite)
	m.HandleFunc("GET "+options.BaseURL+"/invites/{id}/status", wrapper.GetInviteStatus)
	m.HandleFunc("GET "+options.BaseURL+"/persons", wrapper.ListPersons)
	m.HandleFunc("POST "+options.BaseURL+"/persons", wrapper.CreatePerson)
	m.HandleFunc("DELETE "+options.BaseURL+"/persons/{id}", wrapper.DeletePerson)
	m.HandleFunc("GET "+options.BaseURL+"/persons/{id}", wrapper.GetPerson)
	m.HandleFunc("PATCH "+options.BaseURL+"/persons/{id}", wrapper.UpdatePerson)

	return m
}

type ListGroupsRequestObject struct {
}

type ListGroupsResponseObject interface {
	VisitListGroupsResponse(w http.ResponseWriter) error
}

type ListGroups200JSONResponse []Group

func (response ListGroups200JSONResponse) VisitListGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateGroupRequestObject struct {
	Body *CreateGroupJSONRequestBody
}

type CreateGroupResponseObject interface {
	VisitCreateGroupResponse(w http.ResponseWriter) error
}

type CreateGroup201JSONResponse Group

func (response CreateGroup201JSONResponse) VisitCreateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteGroupRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteGroupResponseObject interface {
	VisitDeleteGroupResponse(w http.ResponseWriter) error
}

type DeleteGroup204Response struct {
}

func (response DeleteGroup204Response) VisitDeleteGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteGroup404Response struct {
}

func (response DeleteGroup404Response) VisitDeleteGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetGroupRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetGroupResponseObject interface {
	VisitGetGroupResponse(w http.ResponseWriter) error
}

type GetGroup200JSONResponse Group

func (response GetGroup200JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup404Response struct {
}

func (response GetGroup404Response) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateGroupRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateGroupJSONRequestBody
}

type UpdateGroupResponseObject interface {
	VisitUpdateGroupResponse(w http.ResponseWriter) error
}

type UpdateGroup200JSONResponse Group

func (response UpdateGroup200JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup404Response struct {
}

func (response UpdateGroup404Response) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListGroupMembersRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ListGroupMembersResponseObject interface {
	VisitListGroupMembersResponse(w http.ResponseWriter) error
}

type ListGroupMembers200JSONResponse []Person

func (response ListGroupMembers200JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddGroupMemberRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *AddGroupMemberJSONRequestBody
}

type AddGroupMemberResponseObject interface {
	VisitAddGroupMemberResponse(w http.ResponseWriter) error
}

type AddGroupMember204Response struct {
}

func (response AddGroupMember204Response) VisitAddGroupMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AddGroupMember404Response struct {
}

func (response AddGroupMember404Response) VisitAddGroupMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type RemoveGroupMemberRequestObject struct {
	Id       openapi_types.UUID `json:"id"`
	PersonId openapi_types.UUID `json:"person_id"`
}

type RemoveGroupMemberResponseObject interface {
	VisitRemoveGroupMemberResponse(w http.ResponseWriter) error
}

type RemoveGroupMember204Response struct {
}

func (response RemoveGroupMember204Response) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveGroupMember404Response struct {
}

func (response RemoveGroupMember404Response) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListInvitesRequestObject struct {
}

type ListInvitesResponseObject interface {
	VisitListInvitesResponse(w http.ResponseWriter) error
}

type ListInvites200JSONResponse []Invite

func (response ListInvites200JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateInviteRequestObject struct {
	Body *CreateInviteJSONRequestBody
}

type CreateInviteResponseObject interface {
	VisitCreateInviteResponse(w http.ResponseWriter) error
}

type CreateInvite201JSONResponse Invite

func (response CreateInvite201JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteInviteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteInviteResponseObject interface {
	VisitDeleteInviteResponse(w http.ResponseWriter) error
}

type DeleteInvite204Response struct {
}

func (response DeleteInvite204Response) VisitDeleteInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteInvite404Response struct {
}

func (response DeleteInvite404Response) VisitDeleteInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetInviteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetInviteResponseObject interface {
	VisitGetInviteResponse(w http.ResponseWriter) error
}

type GetInvite200JSONResponse Invite

func (response GetInvite200JSONResponse) VisitGetInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInvite404Response struct {
}

func (response GetInvite404Response) VisitGetInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdateInviteRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateInviteJSONRequestBody
}

type UpdateInviteResponseObject interface {
	VisitUpdateInviteResponse(w http.ResponseWriter) error
}

type UpdateInvite200JSONResponse Invite

func (response UpdateInvite200JSONResponse) VisitUpdateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateInvite404Response struct {
}

func (response UpdateInvite404Response) VisitUpdateInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListInvitePhasesRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type ListInvitePhasesResponseObject interface {
	VisitListInvitePhasesResponse(w http.ResponseWriter) error
}

type ListInvitePhases200JSONResponse []InvitePhase

func (response ListInvitePhases200JSONResponse) VisitListInvitePhasesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvitePhaseRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *CreateInvitePhaseJSONRequestBody
}

type CreateInvitePhaseResponseObject interface {
	VisitCreateInvitePhaseResponse(w http.ResponseWriter) error
}

type CreateInvitePhase201JSONResponse InvitePhase

func (response CreateInvitePhase201JSONResponse) VisitCreateInvitePhaseResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeleteInvitePhaseRequestObject struct {
	Id      openapi_types.UUID `json:"id"`
	PhaseId openapi_types.UUID `json:"phase_id"`
}

type DeleteInvitePhaseResponseObject interface {
	VisitDeleteInvitePhaseResponse(w http.ResponseWriter) error
}

type DeleteInvitePhase204Response struct {
}

func (response DeleteInvitePhase204Response) VisitDeleteInvitePhaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteInvitePhase404Response struct {
}

func (response DeleteInvitePhase404Response) VisitDeleteInvitePhaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type StartInviteRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type StartInviteResponseObject interface {
	VisitStartInviteResponse(w http.ResponseWriter) error
}

type StartInvite200Response struct {
}

func (response StartInvite200Response) VisitStartInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type StartInvite400Response struct {
}

func (response StartInvite400Response) VisitStartInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type StartInvite404Response struct {
}

func (response StartInvite404Response) VisitStartInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetInviteStatusRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetInviteStatusResponseObject interface {
	VisitGetInviteStatusResponse(w http.ResponseWriter) error
}

type GetInviteStatus200JSONResponse InviteStatusReport

func (response GetInviteStatus200JSONResponse) VisitGetInviteStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInviteStatus404Response struct {
}

func (response GetInviteStatus404Response) VisitGetInviteStatusResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type ListPersonsRequestObject struct {
}

type ListPersonsResponseObject interface {
	VisitListPersonsResponse(w http.ResponseWriter) error
}

type ListPersons200JSONResponse []Person

func (response ListPersons200JSONResponse) VisitListPersonsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreatePersonRequestObject struct {
	Body *CreatePersonJSONRequestBody
}

type CreatePersonResponseObject interface {
	VisitCreatePersonResponse(w http.ResponseWriter) error
}

type CreatePerson201JSONResponse Person

func (response CreatePerson201JSONResponse) VisitCreatePersonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeletePersonRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeletePersonResponseObject interface {
	VisitDeletePersonResponse(w http.ResponseWriter) error
}

type DeletePerson204Response struct {
}

func (response DeletePerson204Response) VisitDeletePersonResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeletePerson404Response struct {
}

func (response DeletePerson404Response) VisitDeletePersonResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetPersonRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPersonResponseObject interface {
	VisitGetPersonResponse(w http.ResponseWriter) error
}

type GetPerson200JSONResponse Person

func (response GetPerson200JSONResponse) VisitGetPersonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPerson404Response struct {
}

func (response GetPerson404Response) VisitGetPersonResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type UpdatePersonRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdatePersonJSONRequestBody
}

type UpdatePersonResponseObject interface {
	VisitUpdatePersonResponse(w http.ResponseWriter) error
}

type UpdatePerson200JSONResponse Person

func (response UpdatePerson200JSONResponse) VisitUpdatePersonResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdatePerson404Response struct {
}

func (response UpdatePerson404Response) VisitUpdatePersonResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all groups
	// (GET /groups)
	ListGroups(ctx context.Context, request ListGroupsRequestObject) (ListGroupsResponseObject, error)
	// Create a new group
	// (POST /groups)
	CreateGroup(ctx context.Context, request CreateGroupRequestObject) (CreateGroupResponseObject, error)
	// Delete a group
	// (DELETE /groups/{id})
	DeleteGroup(ctx context.Context, request DeleteGroupRequestObject) (DeleteGroupResponseObject, error)
	// Get a group by ID
	// (GET /groups/{id})
	GetGroup(ctx context.Context, request GetGroupRequestObject) (GetGroupResponseObject, error)
	// Update a group
	// (PATCH /groups/{id})
	UpdateGroup(ctx context.Context, request UpdateGroupRequestObject) (UpdateGroupResponseObject, error)
	// List members of a group
	// (GET /groups/{id}/members)
	ListGroupMembers(ctx context.Context, request ListGroupMembersRequestObject) (ListGroupMembersResponseObject, error)
	// Add a member to a group
	// (POST /groups/{id}/members)
	AddGroupMember(ctx context.Context, request AddGroupMemberRequestObject) (AddGroupMemberResponseObject, error)
	// Remove a member from a group
	// (DELETE /groups/{id}/members/{person_id})
	RemoveGroupMember(ctx context.Context, request RemoveGroupMemberRequestObject) (RemoveGroupMemberResponseObject, error)
	// List all invites
	// (GET /invites)
	ListInvites(ctx context.Context, request ListInvitesRequestObject) (ListInvitesResponseObject, error)
	// Create a new invite
	// (POST /invites)
	CreateInvite(ctx context.Context, request CreateInviteRequestObject) (CreateInviteResponseObject, error)
	// Delete an invite
	// (DELETE /invites/{id})
	DeleteInvite(ctx context.Context, request DeleteInviteRequestObject) (DeleteInviteResponseObject, error)
	// Get an invite by ID
	// (GET /invites/{id})
	GetInvite(ctx context.Context, request GetInviteRequestObject) (GetInviteResponseObject, error)
	// Update an invite
	// (PATCH /invites/{id})
	UpdateInvite(ctx context.Context, request UpdateInviteRequestObject) (UpdateInviteResponseObject, error)
	// List phases for an invite
	// (GET /invites/{id}/phases)
	ListInvitePhases(ctx context.Context, request ListInvitePhasesRequestObject) (ListInvitePhasesResponseObject, error)
	// Add a phase to an invite
	// (POST /invites/{id}/phases)
	CreateInvitePhase(ctx context.Context, request CreateInvitePhaseRequestObject) (CreateInvitePhaseResponseObject, error)
	// Delete a phase from an invite
	// (DELETE /invites/{id}/phases/{phase_id})
	DeleteInvitePhase(ctx context.Context, request DeleteInvitePhaseRequestObject) (DeleteInvitePhaseResponseObject, error)
	// Start the invite process
	// (POST /invites/{id}/start)
	StartInvite(ctx context.Context, request StartInviteRequestObject) (StartInviteResponseObject, error)
	// Get current progress and pending invitees
	// (GET /invites/{id}/status)
	GetInviteStatus(ctx context.Context, request GetInviteStatusRequestObject) (GetInviteStatusResponseObject, error)
	// List all persons
	// (GET /persons)
	ListPersons(ctx context.Context, request ListPersonsRequestObject) (ListPersonsResponseObject, error)
	// Create a new person
	// (POST /persons)
	CreatePerson(ctx context.Context, request CreatePersonRequestObject) (CreatePersonResponseObject, error)
	// Delete a person
	// (DELETE /persons/{id})
	DeletePerson(ctx context.Context, request DeletePersonRequestObject) (DeletePersonResponseObject, error)
	// Get a person by ID
	// (GET /persons/{id})
	GetPerson(ctx context.Context, request GetPersonRequestObject) (GetPersonResponseObject, error)
	// Update a person
	// (PATCH /persons/{id})
	UpdatePerson(ctx context.Context, request UpdatePersonRequestObject) (UpdatePersonResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListGroups operation middleware
func (sh *strictHandler) ListGroups(w http.ResponseWriter, r *http.Request) {
	var request ListGroupsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGroups(ctx, request.(ListGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGroups")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGroupsResponseObject); ok {
		if err := validResponse.VisitListGroupsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateGroup operation middleware
func (sh *strictHandler) CreateGroup(w http.ResponseWriter, r *http.Request) {
	var request CreateGroupRequestObject

	var body CreateGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGroup(ctx, request.(CreateGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateGroupResponseObject); ok {
		if err := validResponse.VisitCreateGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteGroup operation middleware
func (sh *strictHandler) DeleteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteGroupRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteGroup(ctx, request.(DeleteGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteGroupResponseObject); ok {
		if err := validResponse.VisitDeleteGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetGroup operation middleware
func (sh *strictHandler) GetGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetGroupRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroup(ctx, request.(GetGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetGroupResponseObject); ok {
		if err := validResponse.VisitGetGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateGroup operation middleware
func (sh *strictHandler) UpdateGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateGroupRequestObject

	request.Id = id

	var body UpdateGroupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateGroup(ctx, request.(UpdateGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateGroup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateGroupResponseObject); ok {
		if err := validResponse.VisitUpdateGroupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListGroupMembers operation middleware
func (sh *strictHandler) ListGroupMembers(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ListGroupMembersRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListGroupMembers(ctx, request.(ListGroupMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGroupMembers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListGroupMembersResponseObject); ok {
		if err := validResponse.VisitListGroupMembersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddGroupMember operation middleware
func (sh *strictHandler) AddGroupMember(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request AddGroupMemberRequestObject

	request.Id = id

	var body AddGroupMemberJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddGroupMember(ctx, request.(AddGroupMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddGroupMember")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddGroupMemberResponseObject); ok {
		if err := validResponse.VisitAddGroupMemberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveGroupMember operation middleware
func (sh *strictHandler) RemoveGroupMember(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, personId openapi_types.UUID) {
	var request RemoveGroupMemberRequestObject

	request.Id = id
	request.PersonId = personId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveGroupMember(ctx, request.(RemoveGroupMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveGroupMember")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RemoveGroupMemberResponseObject); ok {
		if err := validResponse.VisitRemoveGroupMemberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInvites operation middleware
func (sh *strictHandler) ListInvites(w http.ResponseWriter, r *http.Request) {
	var request ListInvitesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvites(ctx, request.(ListInvitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvites")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInvitesResponseObject); ok {
		if err := validResponse.VisitListInvitesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInvite operation middleware
func (sh *strictHandler) CreateInvite(w http.ResponseWriter, r *http.Request) {
	var request CreateInviteRequestObject

	var body CreateInviteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvite(ctx, request.(CreateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInviteResponseObject); ok {
		if err := validResponse.VisitCreateInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInvite operation middleware
func (sh *strictHandler) DeleteInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteInviteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInvite(ctx, request.(DeleteInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteInviteResponseObject); ok {
		if err := validResponse.VisitDeleteInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInvite operation middleware
func (sh *strictHandler) GetInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetInviteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInvite(ctx, request.(GetInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInviteResponseObject); ok {
		if err := validResponse.VisitGetInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateInvite operation middleware
func (sh *strictHandler) UpdateInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateInviteRequestObject

	request.Id = id

	var body UpdateInviteJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateInvite(ctx, request.(UpdateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateInviteResponseObject); ok {
		if err := validResponse.VisitUpdateInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListInvitePhases operation middleware
func (sh *strictHandler) ListInvitePhases(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ListInvitePhasesRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvitePhases(ctx, request.(ListInvitePhasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvitePhases")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListInvitePhasesResponseObject); ok {
		if err := validResponse.VisitListInvitePhasesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateInvitePhase operation middleware
func (sh *strictHandler) CreateInvitePhase(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request CreateInvitePhaseRequestObject

	request.Id = id

	var body CreateInvitePhaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvitePhase(ctx, request.(CreateInvitePhaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvitePhase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInvitePhaseResponseObject); ok {
		if err := validResponse.VisitCreateInvitePhaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteInvitePhase operation middleware
func (sh *strictHandler) DeleteInvitePhase(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, phaseId openapi_types.UUID) {
	var request DeleteInvitePhaseRequestObject

	request.Id = id
	request.PhaseId = phaseId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteInvitePhase(ctx, request.(DeleteInvitePhaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteInvitePhase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteInvitePhaseResponseObject); ok {
		if err := validResponse.VisitDeleteInvitePhaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartInvite operation middleware
func (sh *strictHandler) StartInvite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request StartInviteRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StartInvite(ctx, request.(StartInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartInvite")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StartInviteResponseObject); ok {
		if err := validResponse.VisitStartInviteResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInviteStatus operation middleware
func (sh *strictHandler) GetInviteStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetInviteStatusRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInviteStatus(ctx, request.(GetInviteStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInviteStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInviteStatusResponseObject); ok {
		if err := validResponse.VisitGetInviteStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPersons operation middleware
func (sh *strictHandler) ListPersons(w http.ResponseWriter, r *http.Request) {
	var request ListPersonsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPersons(ctx, request.(ListPersonsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPersons")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPersonsResponseObject); ok {
		if err := validResponse.VisitListPersonsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePerson operation middleware
func (sh *strictHandler) CreatePerson(w http.ResponseWriter, r *http.Request) {
	var request CreatePersonRequestObject

	var body CreatePersonJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePerson(ctx, request.(CreatePersonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePerson")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePersonResponseObject); ok {
		if err := validResponse.VisitCreatePersonResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeletePerson operation middleware
func (sh *strictHandler) DeletePerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeletePersonRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeletePerson(ctx, request.(DeletePersonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeletePerson")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeletePersonResponseObject); ok {
		if err := validResponse.VisitDeletePersonResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPerson operation middleware
func (sh *strictHandler) GetPerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPersonRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPerson(ctx, request.(GetPersonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPerson")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPersonResponseObject); ok {
		if err := validResponse.VisitGetPersonResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdatePerson operation middleware
func (sh *strictHandler) UpdatePerson(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdatePersonRequestObject

	request.Id = id

	var body UpdatePersonJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdatePerson(ctx, request.(UpdatePersonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdatePerson")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdatePersonResponseObject); ok {
		if err := validResponse.VisitUpdatePersonResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xaW2/bNhT+KwS3hw1QY3ftk9+8FcgyrFnQYk9FYTDisc1WIlmSSmYE/u+DSOpOOVIc",
	"K5enOOblnPN950bSdzgWqRQcuNF4cYd1vIWU2I9LSs+VyORHSK9BfYIfGWiTD0glJCjDwE6ToLTgK0bz",
	"f9ZCpcTgBc4yRnGEzU4CXmBtFOMbvN9HWMGPjCmgePGltvRrOVVcf4PY4H2ErfCuPAo6VkwaJnj+b0tC",
	"hAcpEmFOUgisb2lo19qpIQ0v+A0z0FUxVkAM0BUxDVUoMfDGsBRC+txnFs0UyQdXvIsC/uAHEeOIEy40",
	"xIJTXclh3MAGVL7RWol0uFoD0dSGmMwqBjxLHbec5oMRJrFhN/nmuaclYCDfISY8hiSBOvXVdoaZBIIw",
	"GDFU9xCTbl+PQVTnqTShn+erLdEBsgcixOweq4GzhaKgagDU+NNGEQOb3SoWfM02XWf46/M/l8gNFm6h",
	"JcRszWJkBDJbQMUeOGBsuf93xmmd0YTQXKkIa6kYNwHiQpBXdhdWtUV0Tern4LMl6RNIoQKpyHnaSh5F",
	"FIf/zCreQvx9VPweYEwqsVGg9SoFrckGupT9maWEv1FAKLlOABULUO6nPYTVY69FWJeVDpojvfEGFEmS",
	"VRXlnSk+3FduYw+4gdR++FnBGi/wT7Oq1sx8oZlduYWOXsCVskQpsuv6VN2dmmqFvOYSbh9YRobVh97S",
	"cAm3fdVhZKY/NoOfIJc20uhB63ty5rj0dsIUdUxGuoTbK9vAdO2DlLCkAa775sF9SLG8199aYXSMRqMK",
	"2rgmZ0TT1bC4IS1s/tFEPH7feC9p/8ocrUdPUD1ynkk+ep6tYg9mJw3wlsy9Daq11dpb5bsetLy6wBG+",
	"AaVdv/D2bH42t5VZAieS4QV+dzY/e4cjLInZWhVnm9yv7McN2BjNDbBMXlC8wH8zbc7dlNx3tRRcO+N+",
	"m8/tKUZwA9yuJFImLLZrZ988IK6AD67zzsu75b199MFLlDBtkFgjb0A+RWdpStTOq41IkpSjEZZCB+z7",
	"wzb3TqwLTtDmd0F3o2w7ZFLZXOyb4W9UBvsOpm8fTW5NaBM6ZzJtIea+RQRxuHWo2QneP2Z3jO5dGsgD",
	"rovjB/t9gaMkiqRgQGm8+HKHWS42d7kizS1c6muCEdUMu++G4GsHuPeB8y645LCP8PvQ+KUwaC0y3obC",
	"rUOkgCEKh8Y5mCe0d356R1lWAIzC7xxMAR663qGLDzb8iIm3XRDrxW0qHB8/xutWDArzCdhzOo33freu",
	"8v5WEpil9qJvQMX46Ce+gPAYeAa1VX5UcXJ3lxoxbg/oFaStUuVBzZfU0k64ZDVvXF9w1ISvjgfFT8Cf",
	"l5Qe8HYrCAmFHIuI93j/klJEPB3IiHvDYHZXXk8frI+fIBU3MDFvUXDT6j795BXYWd3Pik8RWyZ7CXFb",
	"VJzYy64GK+7QdzghXfg5U+QJf4IalScKG3q62HL4cBvrJZ+sjy0sm7aRrUsd3cmyYnHlKAN72RLM19HM",
	"8hKK/nb2KU2eT+AvyzoI41vaYvXApnZiNE/V1Y4J+ilIPLav5b05YWafhIYUkis38bV0tvVb+HHtrcMh",
	"ULXcCFoL1Uw995cvp8bLjZrWq8aTFMua6CEV0zW9ljLb894bIrM7+3c1opBORmtP0+v1fQG3To4H1+ce",
	"YEIb4l+3gyH1OR9+8oLeNN3fU1vNgSKdxTFovc6SZOfg6l8TE56fEK6r1b/A2eYsQiRRQOiu/FooxIVP",
	"P7/2kuB37Tt0WPDsid1XfKlErmqYBv9Qcbircr9JeB29VeP3FYEsU/FsMo2Un/cwKvLOK86UAm6qXzwQ",
	"TpF/D0LlbwksN/7C5WANv/JznvmlUd9hsBw+XE295JMVucKyaetbXerow6AsFleOMvAwWIL5Sl42ZOmW",
	"fVnrKS2eT+AuyxoGD3jdcIsHngQnxvJUJ8ExET8FhUe/cJT5YL//PwAA//+Ll5DD4iwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
